### ISSUE TITLE
bug: SDK query methods raise an AttributeError exception when using prefetch_relationships while querying a node that has 0 relations for a relationship

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2412] opened 2024-02-29 21:00 UTC
### Component

Python SDK

### Current Behavior

When you use the `prefetch_relationships=True` argument in the SDK query methods, and the node that you query has 0 relations for a relationship, an AttributeException will be raised.

```python
client.get(kind="InfraInterfaceL3", name__value="Ethernet1", device__name__value="atl1-edge1", prefetch_relationships=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/client.py", line 1092, in get
    results = self.filters(
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/client.py", line 1041, in filters
    process_result: ProcessRelationsNodeSync = self._process_nodes_and_relationships(
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/client.py", line 967, in _process_nodes_and_relationships
    node._process_relationships(node_data=item, branch=branch, related_nodes=related_nodes)
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/node.py", line 1637, in _process_relationships
    related_node = InfrahubNodeSync.from_graphql(
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/node.py", line 1344, in from_graphql
    node_kind = data.get("__typename", None) or data.get("node", {}).get("__typename", None)
AttributeError: 'NoneType' object has no attribute 'get'
```

In this particular case, an InfraInterfaceL3 Node has an optional relationship `connected_endpoint` defined in the schema. The interface that we query has no connected_endpoint relation defined.

### Expected Behavior

No exceptions should be raised in this case, the relationship should be ignored.

### Steps to Reproduce

- start a demo environment `inv demo.start demo.load-infra-schema demo.load-infra-data`
- execute the following python script
```python
from infrahub_sdk import InfrahubClientSync
client = InfrahubClientSync.init()
client.get(kind="InfraInterfaceL3", name__value="Ethernet1", device__name__value="atl1-edge1", prefetch_relationships=True)
```

**Comment by BeArchiTek** [comment] 2024-07-22 11:26
Seem to be fixed with https://github.com/opsmill/infrahub/pull/3039

I can't reproduce the issue with the Demo data and an interface without connected_endpoint

**Closed** 2024-07-22 11:33 UTC
Labels: type/bug, group/python-sdk, state/ref, state/backlog
