### ISSUE TITLE
bug: `IPPrefixPoolGetResource` GraphQL mutation results in an `unknown error`

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3619] opened 2024-06-10 07:59 UTC
### Component

API Server / GraphQL

### Current Behavior

When executing the `IPPrefixPoolGetResource` mutation, you receive an error message `An unknown error occurred.`.

### Expected Behavior

The mutation works, or should return a more descriptive message describing the exact issue

### Steps to Reproduce

load demo schema and data
Replace the id with the id of a IPPrefixPool

```graphql
mutation AllocateIPPrefix {
  IPPrefixPoolGetResource(
    data: {id: "17d792b7-9c36-6254-3583-c5180ce229ee", identifier: "test", member_type: "IpamIPPrefix"}
  ) {
    ok
  }
}
```

**Comment by gmazoyer** [comment] 2024-06-10 12:59
After digging a bit (a lot), it turns out the issue is an invalid value being passed when creating a node. In this particular issue, the `member_type` can only be `prefix` or `address`. So there is a confusion between `member_type` and `prefix_type` (this one take a kind name).

The issue can also raise from the Python SDK functions not exposing the `prefix_type` parameter.

There are nothing to fix here **except** the error message, which is, for one, really confusing and can cause someone to look for an issue for hours.

**Comment by gmazoyer** [comment] 2024-06-14 19:46
Fixed in https://github.com/opsmill/infrahub/commit/50ca75fbeb13f55e5ee2c572350d7e790837f61a

**Closed as completed by gmazoyer** 2024-06-14 19:46 UTC
Labels: type/bug, group/backend
