### ISSUE TITLE
bug: The schema_hash has not been loaded for this branch

### ISSUE THREAD

**Issue by pietos** [opsmill/infrahub#3409] opened 2024-05-22 13:00 UTC
### Current Behavior

On a fresh installation one of our developers gets the following error:

[2m2024-05-20T20:01:15.962019Z[0m [[31m[1merror   [0m][1mTraceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/server.py", line 78, in lifespan
    await app_initialization(application)
  File "/source/backend/infrahub/server.py", line 59, in app_initialization
    await initialization(db=db)
  File "/source/backend/infrahub/core/initialization.py", line 77, in initialization
    hash_in_db = default_branch.active_schema_hash.main
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/branch.py", line 97, in active_schema_hash
    raise InitializationError("The schema_hash has not been loaded for this branch")
infrahub.exceptions.InitializationError: The schema_hash has not been loaded for this branch
[0m [[34m[1muvicorn.error[0m] 
[2m2024-05-20T20:01:15.962292Z[0m [[31m[1merror   [0m][1mApplication startup failed. Exiting.[0m [[34m[1muvicorn.error[0m] 

![photo_2024-05-22_14-06-14 (2)](https://github.com/opsmill/infrahub/assets/58322436/0afdb14d-c6d1-4260-8850-ef29e739b414)

### Steps to Reproduce

Latest code from the Development branch
Docker compose pull
In the compose file only changed the INFRAHUB_ADDRESS & INFRAHUB_INTERNAL_ADDRESS to localhost
docker compose up --build

### Additional Information

Tested on:
Develop branch
Docker 26.1.1
Ubuntu 22.04 LTS 64bit

We tried removing all the volumes and starting from scratch, but he kept having this error.

**Comment by ogenstad** [comment] 2024-07-02 12:29
I'm removing this from the milestones for now as I've not been able to reproduce it, please add more comments if this shows up again.

**Comment by dgarros** [comment] 2024-08-16 04:13
Closing this issue since this hasn't come up recently, please reopen it if the issue is still present

**Closed by dgarros** 2024-08-16 04:13 UTC
Labels: type/bug, group/backend
